stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

deploy-dev:
  stage: deploy
  before_script:
    - export PATH=$PATH:/usr/bin
  script:
    - make build-dev-clean
    - make build-dev
  only:
  - dev
  - feat-39-server