stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

image:
  name: docker/compose:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.17-dind

before_script:
  - docker info
  - docker version

deploy-dev:
  image:
    name: ubuntu:latest
  stage: deploy
  before_script:
    - aptitude -y install docker-compose make
    - ln -s /usr/local/bin/docker-compose /compose/docker-compose
  script:
    - make build-dev-clean
    - make build-dev
  only:
  - dev
  - feat-39-server