stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

image:
  name: docker/compose:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive

services:
  - docker:20.10.17-dind

before_script:
  - docker info
  - docker version

deploy-dev:
  image:
    name: docker/compose:latest
    entrypoint: [ "/bin/sh", "-c" ]
  stage: deploy
  before_script:
    - apt-get update -qq && apt-get install -y -qq make
    - docker-compose version
  script:
    - docker-compose -p "peer_dev"  rm -f -s -v
    - docker-compose -f docker-compose.yml -p "peer_dev" up --build -d
  only:
  - dev
  - feat-39-server