# https://docs.gitlab.com/ee/ci/yaml/

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  - lint

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # force the current docker api version 
  DOCKER_API_VERSION: "1.44"
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

services:
  - docker:dind

# https://stackoverflow.com/questions/36399848/install-node-in-dockerfile

build:
  image:
    name: docker:24.0.7-dind
  stage: build
  #needs: ['test']
  before_script:
    - apk add --no-cache nodejs npm
    - apk add --no-cache make
    - unset DOCKER_HOST
    - docker info
    - docker version
    - TOKEN=$DOCKER_TOKEN
    - echo "$TOKEN" | docker login -u $DOCKER_USER --password-stdin
  script:
    - make ENV=dev build
    - docker wait care_dev-docs_sphinx-1
    - docker compose -p "care_dev"  rm -f -s -v
    - tar -czvf ${PWD}/docs.tar.gz ./docs/build
  artifacts:
    name: "documentation"
    paths:
      - "docs.tar.gz"

.setup-deploy-ssh-template: &setup-ssh
  - apk update && apk add openssh-client
  - mkdir -p ~/.ssh
  - echo "PubkeyAcceptedAlgorithms +ssh-rsa" > ~/.ssh/config
  - echo "HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

deploy-dev:
  stage: deploy
  image: alpine:3.16
  needs: ["build"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && make ENV=dev build-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && make ENV=dev build"
  only:
  - dev

deploy-main:
  stage: deploy
  image: alpine:3.16
  needs: ["build"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && make ENV=main build"
  only:
    - main

lint:
  image:
    name: docker/compose:debian-1.29.2
  stage: lint
  needs: []
  allow_failure: true
  before_script:
    - apk add --no-cache nodejs npm
    - apk add --no-cache make
    - unset DOCKER_HOST
    - docker info
    - docker version
    - TOKEN=$DOCKER_TOKEN
    - echo "$TOKEN" | docker login -u $DOCKER_USER --password-stdin
  script:
    - make lint