# https://docs.gitlab.com/ee/ci/yaml/

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  NODE_VERSION: 16.17.0

services:
  - docker:dind

.setup-nvm-template: &setup-nvm
  - apt update && apt install curl bash -y
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use # load nvm
  - nvm --version
  - eval "[ -f .nvmrc ] && nvm install || nvm install ${NODE_VERSION}"
  - which node
  - echo ${PATH}
  - npm --version
  - node --version

test-backend:
  image:
    name: docker/compose:debian-1.29.2
  stage: test
  needs: []
  before_script:
    - docker info
    - docker version
    - docker-compose version
    - *setup-nvm
    - apk add make postgresql-client
  script:
    - docker-compose -f docker-dev.yml --env-file ".env.test" up -d postgres
    - docker-compose ps
    - make ENV=test test-backend

# https://stackoverflow.com/questions/36399848/install-node-in-dockerfile

test-frontend:
  image:
    name: docker/compose:latest
  stage: test
  needs: []
  before_script:
    - apk add make npm curl bash
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    - source "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION} && nvm use v${NODE_VERSION} && nvm alias default v${NODE_VERSION}
    - PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
    - node --version
    - npm --version
  script:
    - make ENV=test test-frontend

build-dev:
  image:
    name: docker/compose:latest
    entrypoint: [ "/bin/sh", "-c" ]
  stage: build
  needs: ['test-backend', 'test-frontend']
  before_script:
    - docker info
    - docker version
    - apt-get update -qq && apt-get install -y -qq make
    - docker-compose version
  script:
    - docker-compose -f docker-compose.yml -p "peer_dev" --env-file ".env.dev"  up --build -d
    - docker-compose -p "peer_dev"  rm -f -s -v

build-main:
  image:
    name: docker/compose:latest
    entrypoint: [ "/bin/sh", "-c" ]
  stage: build
  needs: ['test-backend', 'test-frontend']
  before_script:
    - docker info
    - docker version
    - apt-get update -qq && apt-get install -y -qq make
    - docker-compose version
  script:
    - docker-compose -f docker-compose.yml -p "peer_main" --env-file ".env.main"  up --build -d


deploy-dev:
  stage: deploy
  image: alpine:latest
  needs: ["build-dev"]
  script:
    - chmod og= $PEER_RSAKEY
    - apk update && apk add openssh-client
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && git fetch"
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && git submodule update --init"
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && make build-dev-clean"
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && make ENV=dev build-dev"
  only:
  - dev

deploy-main:
  stage: deploy
  image: alpine:latest
  needs: ["build-main"]
  script:
    - chmod og= $PEER_RSAKEY
    - apk update && apk add openssh-client
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && git fetch"
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && git submodule update --init"
    - ssh -i $PEER_RSAKEY -o StrictHostKeyChecking=no $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && make ENV=main build"
  only:
    - main