# https://docs.gitlab.com/ee/ci/yaml/

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy
  - lint

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

services:
  - docker:dind

test:
  image:
    name: docker:24.0.7-dind
  stage: test
  needs: []
  allow_failure: true
  before_script:
    - apk add --no-cache make
    - apk add --no-cache nodejs npm
    - docker info
    - docker version
  script:
    - docker compose -f docker-compose.yml -f docker-dev.yml --env-file ".env.test" up -d postgres rpc
    - docker compose ps
    - make ENV=test test

# https://stackoverflow.com/questions/36399848/install-node-in-dockerfile

build:
  image:
    name: docker:24.0.7-dind
  stage: build
  #needs: ['test']
  before_script:
    - apk add --no-cache nodejs npm
    - apk add --no-cache make
    - docker info
    - docker version
  script:
    - make ENV=dev build
    - docker wait care_dev-docs_sphinx-1
    - docker compose -p "care_dev"  rm -f -s -v
    - tar -czvf ${PWD}/docs.tar.gz ./docs/build
    - tar -czvf ${PWD}/doc_api.tar.gz ./docs/api
  artifacts:
    name: "documentation"
    paths:
      - "docs.tar.gz"
      - "doc_api.tar.gz"

.setup-deploy-ssh-template: &setup-ssh
  - apk update && apk add openssh-client
  - mkdir -p ~/.ssh
  - echo "PubkeyAcceptedAlgorithms +ssh-rsa" > ~/.ssh/config
  - echo "HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

deploy-dev:
  stage: deploy
  image: alpine:3.16
  needs: ["build"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && make ENV=dev build-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && make ENV=dev build"
  only:
  - dev

deploy-main:
  stage: deploy
  image: alpine:3.16
  needs: ["build"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd care && make ENV=main build"
  only:
    - main

lint:
  image:
    name: docker/compose:debian-1.29.2
  stage: lint
  needs: []
  allow_failure: true
  before_script:
    - apk add --no-cache nodejs npm
    - apk add --no-cache make
    - docker info
    - docker version
  script:
    - make lint